-- ============================================================
-- RENOMBRADO DE RESTRICCIONES PRIMARY KEY (ENTIDADES PRINCIPALES)
-- ============================================================

ALTER TABLE "ALUMNO"."EMPLEADO" RENAME CONSTRAINT "SYS_C008651" TO "PK_EMPLEADO";
ALTER TABLE "ALUMNO"."CONDUCTOR" RENAME CONSTRAINT "SYS_C008657" TO "PK_CONDUCTOR";
ALTER TABLE "ALUMNO"."MECANICO" RENAME CONSTRAINT "SYS_C008661" TO "PK_MECANICO";
ALTER TABLE "ALUMNO"."CARNET" RENAME CONSTRAINT "SYS_C008689" TO "PK_CARNET";
ALTER TABLE "ALUMNO"."BUS" RENAME CONSTRAINT "SYS_C008681" TO "PK_BUS";
ALTER TABLE "ALUMNO"."CLIENTE" RENAME CONSTRAINT "SYS_C008665" TO "PK_CLIENTE";
ALTER TABLE "ALUMNO"."PASAJERO" RENAME CONSTRAINT "SYS_C008666" TO "PK_PASAJERO";
ALTER TABLE "ALUMNO"."EMPRESA" RENAME CONSTRAINT "SYS_C008668" TO "PK_EMPRESA";
ALTER TABLE "ALUMNO"."BONO" RENAME CONSTRAINT "SYS_C008692" TO "PK_BONO";
ALTER TABLE "ALUMNO"."BILLETE" RENAME CONSTRAINT "SYS_C008685" TO "PK_BILLETE";
ALTER TABLE "ALUMNO"."PIEZA" RENAME CONSTRAINT "SYS_C008688" TO "PK_PIEZA";
ALTER TABLE "ALUMNO"."GERENTE" RENAME CONSTRAINT "SYS_C008653" TO "PK_GERENTE";
ALTER TABLE "ALUMNO"."DEPENDIENTE" RENAME CONSTRAINT "SYS_C008655" TO "PK_DEPENDIENTE";
ALTER TABLE "ALUMNO"."GASOLINERA" RENAME CONSTRAINT "SYS_C008670" TO "PK_GASOLINERA";
ALTER TABLE "ALUMNO"."ESTACION" RENAME CONSTRAINT "SYS_C008672" TO "PK_ESTACION";
ALTER TABLE "ALUMNO"."RUTA" RENAME CONSTRAINT "SYS_C008677" TO "PK_RUTA";
ALTER TABLE "ALUMNO"."PROVEEDOR" RENAME CONSTRAINT "SYS_C008687" TO "PK_PROVEEDOR";
ALTER TABLE "ALUMNO"."TALLER" RENAME CONSTRAINT "SYS_C008659" TO "PK_TALLER";

-- ============================================================
-- RENOMBRADO DE RESTRICCIONES (TABLAS DE RELACIÓN / INTERMEDIAS)
-- ============================================================

ALTER TABLE "ALUMNO"."BUS_LLEVAPOR_PASAJERO" RENAME CONSTRAINT "SYS_C008702" TO "PK_BUS_LLEVAPOR_PASAJERO";
ALTER TABLE "ALUMNO"."MECANICO_REPARA_BUS" RENAME CONSTRAINT "SYS_C008706" TO "PK_MECANICO_REPARA_BUS";
ALTER TABLE "ALUMNO"."DEPENDIENTE_TRABAJA_GASOLINERA" RENAME CONSTRAINT "SYS_C008698" TO "PK_DEP_TRABAJA_GASOLINERA";
ALTER TABLE "ALUMNO"."RUTA_PASAPOR_ESTACION" RENAME CONSTRAINT "SYS_C008696" TO "PK_RUTA_PASAPOR_ESTACION";
ALTER TABLE "ALUMNO"."PROVEEDOR_SUMINISTRA_PIEZA" RENAME CONSTRAINT "SYS_C008711" TO "PK_PROV_SUMINISTRA_PIEZA";

-- Guardar los cambios permanentemente en el diccionario
COMMIT;